name: docker-publish-latest
on:
  push:
    branches:
      - main
      - 'test/*' # my branch just for test
jobs:
  call-base-docker-publish:
    uses: ./.github/workflows/base-docker-publish.yml
    secrets: inherit
    with:
      command: docker-latest
